## 描述器

一个类实现了`__get__`、`__set__`、`__delete__`三个方法，这个类就叫描述器

直接来看一个描述器的实现，如下：


```python
class Number:
    def __init__(self,name):
        self.name = name

    def __get__(self,instance,cls):
        print('call __get__')
        return instance.__dict__[self.name]

    def __set__(self,instance,value):
        print('call __set__')
        if isinstance(value,(int,float)):
            instance.__dict__[self.name] = value
        else:
            raise TypeError('execepted int or float')

    def __delete__(self,instance):
        del instance.__dict__[self.name]
```


```python
class Point:
    x = Number('x')
    y = Number('y')

    def __init__(self,x,y):
        self.x = x
        self.y = y
```

这样就定义了一个描述器`Number`类，这个类的作用是描述实例化`Point`类时`x`和`y`变量的类型必须为整型或浮点型，如果不满足这两种类型中的一个，那抛出TypeError的异常。为了验证代码的调用关系，有意在`Number`类中加了一些`print`语句，在实例代码中应该把这语句去除。现在来实际实例化`Point`类试试：


```python
p1 = Point(2,8)
```

    call __set__
    call __set__


当执行`p1 = Point(2,8)`时发生了什么呢？

1.当python解释器解析到

```py
class Point:
    x = Number('x')
    y = Number('y')

    def __init__(self,x,y):
        self.x = x
        self.y = y
```

代码块时，解释器会创建一个`Point`类对象，此对象中有`x`类变量，且此变量指向`Number`类的一个实例，有`y`类变量，且此变量指向`Number`类的另一个实例；解释器还会创建一个`__init__`函数，此函数接收两个参数。

2.当解释器执行到`p1 = Point(2,8)`时，`Point`类中的`__init__`构建函数被执行，执行以下两代码

```py
self.x = x
self.y = y
```

解释器先执行`self.x = x`代码，这里的`self.x`是一个变量对象，等号后边的`x`是指向类变量`x = Number('x')`中的`Number`类实例，这时解释器会执行`Number`类中的`__set__`函数，把`p1`实例传递给`instance`这个形参，把`2`传递给`value`这个形参，执行此函数体的代码

```
def __set__(self,instance,value):
        print('call __set__')
        if isinstance(value,(int,float)):
            instance.__dict__[self.name] = value
        else:
            raise TypeError('execepted int or float')
```

首先打印出`call __set__`，再执行if语句，为True时把`p1`实例中`__dict__`这个特殊方法中key为`x`的值指向`2`；如果if语句的判断结果为False，那抛出异常。

接着解释器往下执行代码，开始执行构建函数中的`self.y = y`语句，这个过程与执行`self.x = x`语句一样。这样就完成了`p1 = Point(2,8)`这个语句的执行，其**实质就是会去执行Number类的`__set__`函数**



```python
p1.x
```

    call __get__





    2



当执行上边的`p1.x`时发生了什么？

执行`p1.x`是去调用`Point`类的实例变量`x`，从上边的分析可知，这个实例变量是指向`Number('x')`这个实例，这时解释器会执行`Number`类的`__get__`方法，会把`p1`这个实例名作为变量传递给`instance`这个形参，把`p1`的类名作为变量传递给`cls`，代码如下：

```py
def __get__(self,instance,cls):
        print('call __get__')
        return instance.__dict__[self.name]
```
先打印出`call __get__`，然后取出`p1`实例中`__dict__`中key为`x`的值返回，这样就得到执行`p1 = Point(2,8)`语句时`2`这个数字。

总结起来，访问一个使用了描述器的类的实例属性时，**其实质是访问了描述器的`__get__`函数**。

其实访问`p1.x`和访问`Point.x.__get__(p1,Point)`的过程是一样的。


```python
p1.x = 10
```

    call __set__


当执行上边的`p1.x = 10`语句时发生了什么呢？

执行`p1.x = 10`是想把`Point`类的`p1`实例的实例变量指向一个数字`10`，实例变量`x`是指向`Number('x')`这个实例，其实质是去调用`Number`类的`__set__`方法，上边已对调用`__set__`函数进行了详细了分析，不再赘述。

其实执行`p1.x = 10`和执行`Point.x.__set__(p1.10)`的过程是一样的


```python
p1.x
```

    call __get__





    10



再来给`x`一个不是`int`或`float`型的字符，如下：


```python
p1.x = 'zhaochj'
```

    call __set__



    ---------------------------------------------------------------------------

    TypeError                                 Traceback (most recent call last)

    <ipython-input-8-47a1681546d4> in <module>()
    ----> 1 p1.x = 'zhaochj'


    <ipython-input-2-087bfda6d4c9> in __set__(self, instance, value)
         12             instance.__dict__[self.name] = value
         13         else:
    ---> 14             raise TypeError('execepted int or float')
         15
         16     def __delete__(self,instance):


    TypeError: execepted int or float


在类型检查时没有通过，所以抛出我们自定义的异常信息。

在`Point`类中，按理说`类变量x`是可以像`Point.x`来访问的，但执行时，如下：


```python
Point.x
```

    call __get__



    ---------------------------------------------------------------------------

    AttributeError                            Traceback (most recent call last)

    <ipython-input-9-7a7eae6dfbec> in <module>()
    ----> 1 Point.x


    <ipython-input-2-087bfda6d4c9> in __get__(self, instance, cls)
          5     def __get__(self,instance,cls):
          6         print('call __get__')
    ----> 7         return instance.__dict__[self.name]
          8
          9     def __set__(self,instance,value):


    AttributeError: 'NoneType' object has no attribute '__dict__'


这是因为在调用`__get__`方法时`instance`参数接收到了一个`None`对象，这是因为类`Point`并没有被实例化，所以`return`时会报错。可以对`__get__`函数做如下修正，如下：


```python
class NumberFix:
    def __init__(self,name):
        self.name = name

    def __get__(self,instance,cls):
        print('call __get__')
        if instance is not None:
            return instance.__dict__[self.name]
        return self

    def __set__(self,instance,value):
        print('call __set__')
        if isinstance(value,(int,float)):
            instance.__dict__[self.name] = value
        else:
            raise TypeError('execepted int or float')

    def __delete__(self,instance):
        del instance.__dict__[self.name]
```


```python
class Point2:
    x = NumberFix('x')
    y = NumberFix('y')

    def __init__(self,x,y):
        self.x = x
        self.y = y
```


```python
Point2.x
```

    call __get__





    <__main__.NumberFix at 0x7f8030321550>




```python
p2 = Point2(4,7)
```

    call __set__
    call __set__



```python
Point2.x
```

    call __get__





    <__main__.NumberFix at 0x7f8030321550>




```python
p2.x
```

    call __get__





    4




```python
p2.x = 30
```

    call __set__



```python
p2.x
```

    call __get__





    30



这样，`NumberFix`算是一个完整的描述器。

这样，`NumberFix`这个描述器就完成了对实例化类`Point2`时传入参数类型的限制，允许的类型在描述器`NumberFix`的`__set__`函数中进行设置。

上边的例子中都是对各个参数进行同一类型的检查，如果我们要对每个参数都做不同的类型检查呢？比如要求`x`参数为`int`型，`y`参数为`str`型。对上边的描述器做如下改进：


```python
class TypeCheck:
    def __init__(self,name,expected_type):
        self.name = name
        self.expected_type = expected_type

    def __get__(self,instance,cls):
        if instance is not None:
            return instance.__dict__[self.name]
        return self

    def __set__(self,instance,value):
        if not isinstance(value,self.expected_type):
            raise TypeError('expected type {0}'.format(self.expected_type))
        instance.__dict__[self.name] = value

    def __delete__(self,instance):
        del instance.__dict__[self.name]
```


```python
class Point3:
    x = TypeCheck('x',(int,))
    y = TypeCheck('y',(str,))

    def __init__(self,x,y):
        self.x = x
        self.y = y
```


```python
p3 = Point3(10,'zhaochj')
```


```python
p3.x
```




    10




```python
p3.y
```




    'zhaochj'




```python
p3.x = 40
```


```python
p3.x
```




    40




```python
p4 = Point3(10,30)
```


    ---------------------------------------------------------------------------

    TypeError                                 Traceback (most recent call last)

    <ipython-input-67-7765c7ef841b> in <module>()
    ----> 1 p4 = Point3(10,30)


    <ipython-input-58-20cc1f0ef40f> in __init__(self, x, y)
          5     def __init__(self,x,y):
          6         self.x = x
    ----> 7         self.y = y


    <ipython-input-51-d7bab526d123> in __set__(self, instance, value)
         11     def __set__(self,instance,value):
         12         if not isinstance(value,self.expected_type):
    ---> 13             raise TypeError('expected type {0}'.format(self.expected_type))
         14         instance.__dict__[self.name] = value
         15


    TypeError: expected type (<class 'str'>,)


这样就可以实现对不同的变量限制不同的类型，当对`x`和`y`的类型有变更时只需要修改`Point3`类即可。

其实还可以使用装饰器来达到同样的效果，这是一个装饰类`TypeCheck`的装饰器，代码实现如下：


```python
from functools import wraps

def typeinsert(**kwargs):
    def inner(cls):
        @wraps(cls)
        def wrap(**kwargs):
            for k,v in kwargs.items():
                setattr(cls,k,TypeCheck(k,v))
            return cls
        return wrap
    return inner


@typeinsert(x=int,y=float,z=str,m=str)
class Spam:
    def __init__(self,x,y,z,m):
        self.x = x
        self.y = y
        self.z = z
        self.m = m
```


```python
s = Spam(x='dfd',y=10,z=10,m=45)
```




好像没有达到预想的效果，没有想明白，相关视频在“09-面向对象-8”。

**bug修复(2017-5-27)**


问题出在装饰器的部分，装饰器中wrap函数接收的可变关键字参数实质是实质是(x='dfd',y=10,z=10,m=45)，这样通过setattr进行属性的绑定，实质类似这样：`x = TypeCheck(x, 'dfd')`，而不是`x = TypeCheck(x, int)`，所以对装饰器做如下修改：

```python
def typeinsert(**kwargs):
    def inner(cls):
        for k, v in kwargs.items():
           setattr(cls, k, TypeCheck(k, v))
        return cls
    return inner
```

```python
@typeinsert(x=int,y=float,z=str,m=str)
class Spam:
    def __init__(self,x,y,z,m):
        self.x = x
        self.y = y
        self.z = z
        self.m = m
```


```python
s = Spam(x='dfd',y=10,z=10,m=45)
```

报如下错误：

```python
Traceback (most recent call last):
  File "/home/neal/private/sync/my-data/project_deve/monitor_kafka_topics/test/leard.py", line 94, in <module>
    s = Spam(x='dfd', y=10, z=10, m=45)
  File "/home/neal/private/sync/my-data/project_deve/monitor_kafka_topics/test/leard.py", line 89, in __init__
    self.x = x
  File "/home/neal/private/sync/my-data/project_deve/monitor_kafka_topics/test/leard.py", line 67, in __set__
    raise TypeError('expected type {0}'.format(self.expected_type))
TypeError: expected type <class 'int'>
```

再按照规定的类型进行传递参数：

```python
s = Spam(x=10, y=10.3, z='zhaochj', m='zcj')
```

这样是没有问题的。如果一个参数是可以允许多个类型的，那以元组的方式来制定：

```python
@typeinsert(x=(int, float), y=float, z=str, m=str)
...
```
